FROM golang:1.24 AS builder

WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .
RUN mkdir /old-logs
RUN CGO_ENABLED=0 GOOS=linux go build -o /app -a -ldflags '-w -s' ./PingUtility

FROM scratch
COPY --from=builder /old-logs /old-logs
COPY --from=builder /app /pingutility-server
ENTRYPOINT ["/pingutility-server"]